baseURL = 'https://www.gx1.me/'
theme = 'm10c'
languageCode = 'en-us'
title = 'Gx1 Website'
enableEmoji = true

[params]
avatar = 'avatar.png'
description = "Hi folks, here you find my thoughts about development, security, and research."


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "sec"
    name = "Security"
    url = "/sec/"
    weight = 2
  
  [[menu.main]]
    identifier = "dev"
    name = "Development"
    url = "/dev/"
    weight = 3
    
  #[[menu.main]]
  #  identifier = "research"
  #  name = "Research"
  #  url = "/research/"
  #  weight = 4

  
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 5
  
  [[menu.main]]
  identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6


[params.style]
  #darkestColor = "#d35050"
  #darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#d35100"


  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/giper45"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/g_per45"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/gaetano-perrone-60520961/"


  [[params.social]]
    icon = "mail"
    name = "Mail"
    url = "mailto:g.per45@gmail.com"
